fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "update_status",
            "update_open_release",
            "current_form",
            "save_current_form",
            "update_initialized",
            "update_reserve",
            "update_ack",
            "update_release",
            "update_install",
            "update_lease_alive",
            "update_invalidate",
            "update_final_ack",
            "open_game",
            "close_game",
            "control_bot",
            "bridge_status",
            "login_game",
            "reconnect_game",
            "saved_login",
            "forget_login",
            "cancel_pending_login",
            "take_pending_login",
        ]),
    ))
    .expect("Tauri build configuration must be valid");
}
