import { describe, expect, it } from 'vitest';
import { ManualMemo, memoPreview, type MemoContext } from './memo';
import type { MemoSlots } from './memo-protocol';
const context:MemoContext={ready:true,idle:true,world:'00000000-0000-4000-8000-000000000001',actorId:1,incarnation:1,connectionEpoch:1,map:'prt_fild08',x:10,y:20,walkable:true,canMemo:true,learnedWarp:4};
const empty:MemoSlots=[null,null,null,null];
function fixture(){let now=1000;const sent:number[]=[];const model=new ManualMemo(slot=>sent.push(slot),()=>now);model.observeSlots(empty,context);return{model,sent,request:()=>memoPreview(model.snapshot(context),0).request!,advance:(ms:number)=>{now+=ms;model.tick(context);}};}
const saved:MemoSlots=[{map:context.map,x:context.x,y:context.y},null,null,null];
describe('explicit memo revision and receipt ownership',()=>{
 it('retains initial pre-spawn state without authorizing any send',()=>{const t=fixture();t.model.reset('Enter');t.model.observeSlots(empty,{...context,ready:false,actorId:null,incarnation:null});expect(t.model.snapshot({...context,ready:false}).slots).toEqual(empty);expect(t.model.snapshot({...context,ready:false}).ready).toBeNull();expect(t.model.snapshot(context).ready).not.toBeNull();expect(t.sent).toEqual([]);});
 it('confirms only an ordered exact notification and complete readback',()=>{const t=fixture();const request=t.request();expect(t.sent).toEqual([]);t.model.dispatch(request,context);expect(t.model.snapshot(context).state).toBe('sent');expect(()=>t.model.dispatch(request,context)).toThrow();t.model.observeNotification(0,context);expect(t.model.snapshot(context).state).toBe('notified');t.model.observeSlots(saved,context);expect(t.model.snapshot(context).state).toBe('confirmed');expect(t.sent).toEqual([0]);});
 it('rejects stale previews, missing/granted-only prerequisites and all unknown permission/motion state',()=>{for(const change of [{ready:false},{actorId:null},{incarnation:null},{idle:false},{learnedWarp:null},{learnedWarp:0},{canMemo:null},{canMemo:false},{walkable:null},{walkable:false}]){const t=fixture();expect(()=>t.model.dispatch(t.request(),{...context,...change})).toThrow();expect(t.sent).toEqual([]);}const t=fixture(),request=t.request();t.model.observeSlots(empty,context);expect(()=>t.model.dispatch(request,context)).toThrow('stale');const next=t.request();t.model.cancel('Stop');expect(()=>t.model.dispatch(next,context)).toThrow('stale');expect(()=>t.model.dispatch({...t.request(),slot:3},{...context,learnedWarp:3})).toThrow('higher');});
 it('makes an already identical slot a packet-free no-op',()=>{const t=fixture();t.model.observeSlots(saved,context);expect(memoPreview(t.model.snapshot(context),0).request).toBeNull();t.model.dispatch({type:'memoSave',slot:0,preview:t.model.snapshot(context).ready},context);expect(t.model.snapshot(context).state).toBe('alreadyCurrent');expect(t.sent).toEqual([]);});
 it('holds wrong slots, duplicates, unordered/no-change/contradictory readbacks as uncertain',()=>{for(const outcome of ['wrong','duplicate','unordered','nochange','untouched']){const t=fixture();t.model.dispatch(t.request(),context);if(outcome==='wrong')t.model.observeNotification(1,context);else if(outcome!=='unordered'){t.model.observeNotification(0,context);if(outcome==='duplicate')t.model.observeNotification(0,context);}t.model.observeSlots(outcome==='nochange'?empty:outcome==='untouched'?[saved[0],{map:'other',x:1,y:2},null,null]:saved,context);expect(t.model.snapshot(context).state).toBe('uncertain');expect(t.sent).toEqual([0]);if(t.model.blocked)t.model.observeSlots(saved,context);expect(t.model.blocked).toBe(false);}});
 it('never lets timeout, canceled, late or identical repeats complete a newer intent',()=>{const t=fixture();t.model.dispatch(t.request(),context);t.advance(10000);expect(t.model.blocked).toBe(true);expect(t.model.snapshot(context).state).toBe('uncertain');t.model.observeNotification(0,context);t.model.observeSlots(empty,context);t.model.dispatch(t.request(),context);t.model.observeNotification(0,context);t.model.observeSlots(saved,context);expect(t.model.snapshot(context).state).toBe('uncertain');expect(t.sent).toEqual([0,0]);t.model.cancel('Stop');t.model.reset('Reconnect');t.advance(20000);expect(t.sent).toEqual([0,0]);});
 it('fences character, connection, world and physical-cell replacement and unknown own zero',()=>{for(const change of [{actorId:2},{incarnation:2},{connectionEpoch:2},{world:'00000000-0000-4000-8000-000000000002'},{map:'prt_fild07'},{x:11},{ready:false}]){const t=fixture();t.model.dispatch(t.request(),context);t.model.tick({...context,...change});t.model.observeNotification(0,{...context,...change});t.model.observeSlots(saved,{...context,...change});expect(t.model.snapshot(context).state).toBe('uncertain');expect(t.sent).toEqual([0]);}const t=fixture();expect(()=>t.model.dispatch({...t.request(),preview:{...t.request().preview,actorId:0}},{...context,ready:false,actorId:0})).toThrow();});
 it('does not retry transport errors or unsolicited observations',()=>{const m=new ManualMemo(()=>{throw new Error('synthetic');});m.observeSlots(empty,context);expect(()=>m.dispatch(memoPreview(m.snapshot(context),0).request,context)).toThrow('uncertain');expect(m.blocked).toBe(true);m.tick();m.observeSlots(saved,context);expect(m.snapshot(context).state).toBe('uncertain');const t=fixture();t.model.observeNotification(1,context);expect(t.model.snapshot(context).slots).toBeNull();expect(t.sent).toEqual([]);});
 it('fails attribution closed once the bounded fingerprint budget fills, and fences clock rollback',()=>{const t=fixture();for(let x=0;x<130;x++){const c={...context,x};t.model.observeSlots(empty,c);t.model.dispatch(memoPreview(t.model.snapshot(c),0).request,c);t.model.observeNotification(0,c);t.model.observeSlots([{map:c.map,x,y:c.y},null,null,null],c);expect(t.model.snapshot(c).state).toBe(x<128?'confirmed':'uncertain');}expect(t.model.snapshot(context).state).toBe('uncertain');expect(t.sent).toHaveLength(130);t.model.observeSlots(empty,context);t.model.dispatch(t.request(),context);t.advance(-1);expect(t.model.snapshot(context).state).toBe('uncertain');expect(t.model.blocked).toBe(true);});
});
